image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
 - bauen
 - testen

build:
  stage: bauen
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: testen
  script:
    - mvn $MAVEN_CLI_OPTS test